{
 "title": "System Monitor MySQL",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT `time`, `cpu-usage` FROM `CPU_usage` \n"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "system-monitor",
     "rawSql": "SELECT `time`, `cpu-usage` FROM `CPU_usage` \n"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT `time`, `temperature` FROM `CPU_temp` \r\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT `time`, `ram-usage` FROM `RAM_usage` "
    }
   ]
  },
  {
   "title": "Memory Availability",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT `time`, `available` FROM `RAM_usage`"
    },
    {
     "rawSql": "SELECT ram_size, system_id FROM `System` WHERE system_id=1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT `used` FROM `DISK_usage` "
    },
    {
     "rawSql": "SELECT disk_size, system_id FROM `System` WHERE system_id=1\n"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT `time`, `disk-usage` FROM `DISK_usage` "
    }
   ]
  },
  {
   "title": "Disk availability ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT `time`, `available` FROM `DISK_usage` "
    },
    {
     "rawSql": "SELECT disk_size, system_id FROM `System` WHERE system_id=1\n"
    }
   ]
  },
  {
   "title": "Received bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  `time`,\r\n  `network-usage`\r\nFROM\r\n  `NETWORK_usage`\r\nWHERE \r\n  `type`='received'"
    }
   ]
  },
  {
   "title": "Transmitted bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  `time`,\r\n  `network-usage`\r\nFROM\r\n  `NETWORK_usage`\r\nWHERE \r\n  `type`='transmitted'"
    }
   ]
  },
  {
   "title": "Received bytes total",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  `time`,\r\n  `network-usage`\r\nFROM\r\n  `NETWORK_usage`\r\nWHERE \r\n  `type`='received'"
    }
   ]
  },
  {
   "title": "Transmitted bytes total",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  `time`,\r\n  `network-usage`\r\nFROM\r\n  `NETWORK_usage`\r\nWHERE \r\n  `type`='transmitted'"
    }
   ]
  }
 ]
}